# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  # Box Settings
  config.vm.box = "ubuntu/bionic64"

  # Provider Settings
  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = true
  
    # Customize the amount of memory on the VM:
    vb.memory = "1024"
  end

  # Network Settings
  # config.vm.network "forwarded_port", guest: 80, host: 8080
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  config.vm.network "private_network", ip: "192.168.56.100"
  # config.vm.network "public_network"

  # Folder Settings
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provision Settings
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install wget
    wget https://raw.githubusercontent.com/wuvel/Administrasi-Sistem-Server/master/Web/installManual.sh
    chmod +x installManual.sh
    ./installManual.sh https://github.com/wuvel/simple-php.git
  SHELL
end
