# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  # Box Settings
  config.vm.box = "ubuntu/bionic64"

  # Network settings
  config.vm.network "private_network", ip: "192.168.56.100"

  # Provider Settings
  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    # vb.gui = true
  
    # Customize the amount of memory on the VM:
    vb.memory = "1024"
  end
  
  # Provisioning with script.sh
  config.vm.provision :shell, path: "installManual.sh" 


end
